site_name: MicroDataflake
site_url: https://alvsanand.github.io/micro-dataflake/
site_author: Alvaro Santos Andres
site_description: >-
  MicroDataflake is a powerful data platform designed for edge devices, enabling seamless analytics and insights in your home environment.


repo_name: alvsanand/micro-dataflake
repo_url: https://github.com/alvsanand/micro-dataflake

theme:
  name: material
  icon:
    logo: material/library
  palette:
    primary: blue grey
    scheme: slate
  features:
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - blog
