site_name: DataHub.local
site_url: https://alvsanand.github.io/datahub-local/
site_author: Alvaro Santos Andres
site_description: >-
  DataHub.local is a powerful data platform designed for edge devices, enabling seamless analytics and insights at home.

repo_name: alvsanand/datahub-local
repo_url: https://github.com/alvsanand/datahub-local

theme:
  name: material
  icon:
    logo: material/library
  palette:
    primary: blue grey
    scheme: slate
  features:
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.integration
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - macros:
      include_dir: .
  - glightbox

nav:
  - Home: index.md
  - Cluster Setup:
      - Hardware: cluster_setup/hardware.md
      - Bootstrapping: cluster_setup/bootstrapping.md
