site_name: DataHub.local
site_url: https://alvsanand.github.io/datahub-local/
site_author: Alvaro Santos Andres
site_description: >-
  DataHub.local is a powerful data platform designed for edge devices, enabling seamless analytics and insights at home.


repo_name: alvsanand/datahub-local
repo_url: https://github.com/alvsanand/datahub-local

theme:
  name: material
  icon:
    logo: material/library
  palette:
    primary: blue grey
    scheme: slate
  features:
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.integration
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - macros:
      include_dir: .
  - glightbox
